"""
PROJECT JANUS MINI (16-TILE): AUTOMATED MODULI & CRT CONSTANTS GENERATOR
========================================================================
Single Source of Truth Code Generator.
Reads canonical moduli specification from configs/moduli.json and generates:
  1. janus_moduli_params.vh (Verilog parameters header)
  2. Validates mathematical correctness and coprimality
"""

import json
import os
import math
from typing import Tuple, List, Dict


def extended_gcd(a: int, b: int) -> Tuple[int, int, int]:
    if a == 0:
        return b, 0, 1
    gcd_val, x1, y1 = extended_gcd(b % a, a)
    x = y1 - (b // a) * x1
    y = x1
    return gcd_val, x, y


def mod_inverse(a: int, m: int) -> int:
    gcd_val, x, _ = extended_gcd(a % m, m)
    if gcd_val != 1:
        raise ValueError(f"Modular inverse does not exist for a={a}, m={m}")
    return (x % m + m) % m


def generate_verilog_header(json_path: str, output_vh_path: str):
    with open(json_path, 'r', encoding='utf-8') as f:
        spec = json.load(f)

    compute_mods = [item["modulus"] for item in spec["compute_moduli"]]
    red_mods = [item["modulus"] for item in spec["redundant_moduli"]]

    # Verify pairwise coprimality
    all_mods = compute_mods + red_mods
    for i in range(len(all_mods)):
        for j in range(i + 1, len(all_mods)):
            g = math.gcd(all_mods[i], all_mods[j])
            assert g == 1, f"Moduli {all_mods[i]} and {all_mods[j]} are not coprime (gcd={g})!"

    M_TOTAL = 1
    for m in compute_mods:
        M_TOTAL *= m

    mi_list = []
    ni_list = []
    for m in compute_mods:
        mi = M_TOTAL // m
        ni = mod_inverse(mi, m)
        assert (mi * ni) % m == 1
        mi_list.append(mi)
        ni_list.append(ni)

    lines = [
        "// ==============================================================================",
        "// PROJECT JANUS MINI (16-TILE): AUTO-GENERATED CRT & MODULI PARAMETERS",
        "// ==============================================================================",
        "// DO NOT EDIT MANUALLY. Generated by generate_moduli_constants.py from configs/moduli.json.",
        "// Provides Single Source of Truth for CRT Adder Tree, RNS Encoders & JIR Monitor.",
        "// ==============================================================================",
        "",
        f"// Total Dynamic Range Modulus ({M_TOTAL.bit_length()}-bit product of 16 compute moduli)",
        f"localparam [127:0] M_TOTAL    = 128'h{M_TOTAL:032x};",
        "localparam [139:0] M_TOTAL_X8 = {9'b0,  M_TOTAL, 3'b000}; // 8 * M_TOTAL",
        "localparam [139:0] M_TOTAL_X4 = {10'b0, M_TOTAL, 2'b00};  // 4 * M_TOTAL",
        "localparam [139:0] M_TOTAL_X2 = {11'b0, M_TOTAL, 1'b0};   // 2 * M_TOTAL",
        "localparam [139:0] M_TOTAL_X1 = {12'b0, M_TOTAL};         // 1 * M_TOTAL",
        "",
        "// Redundant Moduli for JIR Parity",
        f"localparam [8:0] RED_M0 = 9'd{red_mods[0]};",
        f"localparam [8:0] RED_M1 = 9'd{red_mods[1]};",
        "",
        "// JIR Diagnostic Fault IDs",
        "localparam [4:0] FID_HEALTHY       = 5'd0;  // Healthy traffic",
        "localparam [4:0] FID_COMPUTE_TILE  = 5'd1;  // Primary Compute Tile / CRT error (SFA)",
        "localparam [4:0] FID_RED0_PARITY   = 5'd16; // Redundant Modulus 0 parity error",
        "localparam [4:0] FID_RED1_PARITY   = 5'd17; // Redundant Modulus 1 parity error",
        "localparam [4:0] FID_PROTOCOL_SYNC = 5'd30; // Pipeline synchronization / valid divergence",
        "localparam [4:0] FID_MULTI_FAULT   = 5'd31; // Unresolvable / Multiple-Fault syndrome",
        "",
        "// Moduli Constants (m_i), CRT Multipliers (N_i), and CRT Basis Weights (MI_i)",
    ]

    for i in range(16):
        m = compute_mods[i]
        n = ni_list[i]
        mi = mi_list[i]
        lines.append(f"localparam [8:0]   M_{i:<2} = 9'd{m};")
        lines.append(f"localparam [8:0]   N_{i:<2} = 9'd{n};")
        lines.append(f"localparam [127:0] MI_{i:<2} = 128'h{mi:032x};")

    lines.extend([
        ""
    ])

    content = "\n".join(lines)
    with open(output_vh_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"[OK] Successfully generated {output_vh_path} from {json_path}")
    print(f"     M_TOTAL bit-length: {M_TOTAL.bit_length()} bits, 16 compute channels, 2 redundant channels.")


if __name__ == "__main__":
    tier4_dir = os.path.dirname(os.path.abspath(__file__))
    configs_dir = os.path.join(tier4_dir, "..", "configs")
    json_path = os.path.join(configs_dir, "moduli.json")
    output_vh_path = os.path.join(tier4_dir, "janus_moduli_params.vh")
    generate_verilog_header(json_path, output_vh_path)
